WeBankFinTech/Exchangis

modules/service/src/main/java/com/webank/wedatasphere/exchangis/project/controller/ProjectController.java
modules/service/src/main/java/com/webank/wedatasphere/exchangis/project/dao/ProjectDao.java
modules/service/src/main/java/com/webank/wedatasphere/exchangis/project/domain/Project.java
modules/service/src/main/java/com/webank/wedatasphere/exchangis/project/query/ProjectQuery.java
modules/service/src/main/java/com/webank/wedatasphere/exchangis/project/service/ProjectService.java
modules/service/src/main/java/com/webank/wedatasphere/exchangis/project/service/impl/ProjectServiceImpl.java
modules/service/src/main/java/com/webank/wedatasphere/exchangis/tab/TabController.java
modules/service/src/main/java/com/webank/wedatasphere/exchangis/tab/dao/TabDao.java
modules/service/src/main/java/com/webank/wedatasphere/exchangis/tab/domain/TabEntity.java
modules/service/src/main/java/com/webank/wedatasphere/exchangis/tab/service/TabService.java
modules/service/src/main/java/com/webank/wedatasphere/exchangis/tab/service/impl/TabServiceImpl.java

Project and tab management modules.

Submit project and tab management modules.

---

sources/web-design/fes.config.js
sources/web-design/src/app.js

已登录新打开窗口路由跳转错误修复

---

sources/web-design/en.json
sources/web-design/src/pages/ds/dataTemplate/index.fes
sources/web-design/zh.json

oracle模板创建参数校验

---

modules/service/src/main/java/com/webank/wedatasphere/exchangis/http/converters/CustomHttpMessageConverter.java

enable the  customer json message converter date config

jackson date config

---

bin/exchangis-init.sql
modules/service/src/main/java/com/webank/wedatasphere/exchangis/project/service/impl/ProjectServiceImpl.java
modules/service/src/main/resources/i18n/messages.properties
modules/service/src/main/resources/i18n/messages_en_US.properties
modules/service/src/main/resources/i18n/messages_zh_CN.properties

add UNIQUE key check for exchangis_project, at sql and java code.

add UNIQUE key check for exchangis_project

---

modules/service/src/main/resources/job_templates/datax/readers/hive.tpl

hive.tpl miss the kerberos config item  hivePrincipal.

resolve the hive reader  problem when  with kerberos  auth

---

modules/service/src/main/java/com/webank/wedatasphere/exchangis/datasource/conns/MySQL.java

MySQL#getAllDBdatas  function miss the parameter that   added in datasource template.

add jdbc url parameter for show database feture when config mysql datasource

---

exchangis-dao/src/main/java/com/webank/wedatasphere/exchangis/dao/domain/ExchangisJobParamConfig.java
exchangis-job/exchangis-job-common/src/main/java/com/webank/wedatasphere/exchangis/job/vo/ExchangisJobVO.java
exchangis-job/exchangis-job-launcher/src/main/java/com/webank/wedatasphere/exchangis/job/launcher/entity/ExchangisTaskEntity.java
exchangis-job/exchangis-job-launcher/src/main/java/com/webank/wedatasphere/exchangis/job/launcher/entity/GenericExchangisTaskEntity.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/dao/ExchangisJobEntityDao.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/dao/LaunchedTaskDao.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/dto/ExchangisJobBasicInfoDTO.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/mapper/impl/ExchangisJobEntityDao.xml
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/mapper/impl/LaunchedJobMapper.xml
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/mapper/impl/LaunchedTaskMapper.xml
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/service/ExchangisExecutionService.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/service/impl/ExchangisExecutionServiceImpl.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/service/impl/ExchangisJobServiceImpl.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/vo/ExchangisJobProgressVo.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/vo/ExchangisJobTaskVo.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/vo/ExchangisProgressVo.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/web/ExchangisJobExecuteController.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/web/ExchangisTaskExecuteController.java

Available execution interfaces

---

exchangis-datasource/exchangis-datasource-core/src/main/java/com/webank/wedatasphere/exchangis/datasource/core/ui/ElementUI.java
exchangis-datasource/exchangis-datasource-core/src/main/java/com/webank/wedatasphere/exchangis/datasource/core/ui/ExchangisDataSourceParamsUI.java
exchangis-datasource/exchangis-datasource-core/src/main/java/com/webank/wedatasphere/exchangis/datasource/core/ui/InputElementUI.java
exchangis-datasource/exchangis-datasource-core/src/main/java/com/webank/wedatasphere/exchangis/datasource/core/ui/OptionElementUI.java
exchangis-datasource/exchangis-datasource-core/src/main/java/com/webank/wedatasphere/exchangis/datasource/core/ui/viewer/DefaultDataSourceUIViewer.java
exchangis-datasource/exchangis-datasource-core/src/main/java/com/webank/wedatasphere/exchangis/datasource/core/ui/viewer/ExchangisDataSourceUIViewer.java
exchangis-datasource/exchangis-datasource-core/src/main/java/com/webank/wedatasphere/exchangis/datasource/core/vo/ExchangisJobParamsContent.java
exchangis-datasource/exchangis-datasource-service/src/main/java/com/webank/wedatasphere/exchangis/datasource/service/AbstractDataSourceService.java
exchangis-datasource/exchangis-datasource-service/src/main/java/com/webank/wedatasphere/exchangis/datasource/service/DataSourceUIGetter.java
exchangis-datasource/exchangis-datasource-service/src/main/java/com/webank/wedatasphere/exchangis/datasource/service/ExchangisDataSourceService.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/service/ExchangisJobService.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/service/impl/DefaultJobExecuteService.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/service/impl/ExchangisJobServiceImpl.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/web/ExchangisJobController.java

Adjust the interface of UI Element

Change the value type of UIElement to generic type

---

exchangis-job/exchangis-job-launcher/src/main/java/com/webank/wedatasphere/exchangis/job/launcher/linkis/LinkisLauncherTask.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/execution/loadbalance/FlexibleTenancyLoadBalancer.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/mapper/impl/LaunchedTaskMapper.xml
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/service/impl/DefaultJobExecuteService.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/service/impl/DefaultTaskExecuteService.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/vo/ExchangisJobTaskVo.java

Fix some problem in fetching logs and updating job state

Fix some problem in fetching logs and updating job state

---

exchangis-plugins/engine/datax/datax-assembly/package.xml
exchangis-plugins/engine/datax/datax-assembly/pom.xml
exchangis-plugins/engine/datax/datax-core/pom.xml
exchangis-plugins/engine/datax/datax-elasticsearchwriter/pom.xml
exchangis-plugins/engine/datax/datax-elasticsearchwriter/src/main/java/com/webank/wedatasphere/exchangis/datax/plugin/writer/elasticsearchwriter/v6/ElasticRestClient.java
exchangis-plugins/engine/datax/datax-ftpreader/pom.xml
exchangis-plugins/engine/datax/datax-ftpwriter/pom.xml
exchangis-plugins/engine/datax/datax-hdfsreader/pom.xml
exchangis-plugins/engine/datax/datax-hdfswriter/pom.xml
exchangis-plugins/engine/datax/datax-mysqlreader/pom.xml
exchangis-plugins/engine/datax/datax-mysqlwriter/pom.xml
exchangis-plugins/engine/datax/datax-oraclereader/pom.xml
exchangis-plugins/engine/datax/datax-oraclewriter/pom.xml
exchangis-plugins/engine/datax/datax-textfilereader/pom.xml
exchangis-plugins/engine/datax/datax-textfilewriter/pom.xml
exchangis-plugins/engine/datax/pom.xml
exchangis-plugins/exchangis-appconn/pom.xml
exchangis-plugins/pom.xml
pom.xml

Dev 1.0.0 datax

---

exchangis-dao/src/main/java/com/webank/wedatasphere/exchangis/dao/domain/ExchangisJobParamConfig.java
exchangis-datasource/exchangis-datasource-server/src/main/java/com/webank/wedatasphere/exchangis/datasource/server/restful/api/ExchangisDataSourceRenderRestfulApi.java
exchangis-datasource/exchangis-datasource-server/src/main/java/com/webank/wedatasphere/exchangis/datasource/server/restful/api/ExchangisDataSourceRestfulApi.java
exchangis-datasource/exchangis-datasource-server/src/main/java/com/webank/wedatasphere/exchangis/datasource/server/restful/api/ExchangisJobDataSourceRestfulApi.java
exchangis-datasource/exchangis-datasource-service/src/main/java/com/webank/wedatasphere/exchangis/datasource/service/ExchangisDataSourceService.java
exchangis-datasource/exchangis-datasource-service/src/main/scala/com/webank/wedatasphere/exchangis/datasource/GetDataSourceInfoByIdAndVersionIdAction.scala
exchangis-job/exchangis-job-metrics/src/main/java/com/webank/wedatasphere/exchangis/metrics/service/impl/ExchangisMetricsServiceImpl.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/log/service/LocalSimpleJobLogService.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/restful/ExchangisJobRestfulApi.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/restful/ExchangisMetricsRestfulApi.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/restful/ExchangisTaskRestfulApi.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/restful/execute/ExchangisJobExecuteRestfulApi.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/restful/execute/ExchangisTaskExecuteRestfulApi.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/restful/external/ExchangisJobDssAppConnRestfulApi.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/service/impl/DefaultJobInfoService.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/service/impl/ExchangisMetricsServiceImpl.java
exchangis-plugins/exchangis-appconn/src/main/java/com/webank/wedatasphere/exchangis/dss/appconn/constraints/Constraints.java
exchangis-plugins/exchangis-appconn/src/main/java/com/webank/wedatasphere/exchangis/dss/appconn/operation/ref/ExchangisRefUpdateOperation.java
exchangis-project/exchangis-project-server/src/main/java/com/webank/wedatasphere/exchangis/project/server/restful/ExchangisProjectRestfulApi.java
web/src/pages/dataSourceManage/index.vue

Adding an url access prefix (/main), For example, dss/exchangis/datasources  changes to   dss/exchangis/main/datasources

增加url前缀(/main)

---

docs/zh_CN/ch1/exchangis_sqoop_deploy_cn.md
exchangis-plugins/engine/sqoop/pom.xml
exchangis-plugins/pom.xml

Related issues: #50. )
(for example:)
- fix pom about sqoop
- fix exchangis_sqoop_deploy_cn.md
- Dependencies (does it add or upgrade a dependency): (yes)
- Anything that affects deployment: (yes)
- The Core framework, i.e., JobManager, Server.: (yes)
- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (docs)

Fix: sqoop engine

---

docs/zh_CN/ch1/exchangis_deploy_cn.md

Modify exchangis_deploy_cn.md
(for example:)
- Modify the usage of the installation script
- Modify the use of daemon.sh
(Please pick either of the following options)  
This change is already covered by existing tests, such as (please describe tests).  
- Dependencies (does it add or upgrade a dependency): (yes / no)no
- Anything that affects deployment: (yes / no / don't know)no
- The Core framework, i.e., JobManager, Server.: (yes / no)no
- Does this pull request introduce a new feature? (yes / no)no
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

Modify exchangis_deploy_cn.md

---

db/exchangis_ddl.sql
exchangis-plugins/exchangis-appconn/src/main/resources/init.sql

Related issues: #50. )
(for example:)
- fix init.sql;
- fix exchangis_ddl.sql.
- Dependencies (does it add or upgrade a dependency): (no)
- Anything that affects deployment: (yes)
- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (not applicable)

fix init.sql and exchangis_ddl.sql

---

exchangis-plugins/exchangis-appconn/src/main/resources/init.sql

Related issues: #50. )
(for example:)
- fix init.sql.
- Dependencies (does it add or upgrade a dependency): (no)
- Anything that affects deployment: (no)
- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (not applicable)

fix init.sql

---

db/exchangis_ddl.sql

- fix exchangis_ddl.sql.
(for example:)
- fix exchangis_ddl.sql.
- Dependencies (does it add or upgrade a dependency): (yes)
- Anything that affects deployment: (yes)
- Does this pull request introduce a new feature? (yes)
- If yes, how is the feature documented? (docs)

fix exchangis_ddl.sql

---

exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/execution/AbstractTaskExecution.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/execution/TaskExecutionListener.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/execution/events/TaskDequeueEvent.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/execution/loadbalance/FlexibleTenancyLoadBalancer.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/execution/scheduler/ExchangisGenericScheduler.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/execution/scheduler/ExchangisSchedulerContext.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/execution/scheduler/tasks/SubmitSchedulerTask.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/execution/subscriber/AbstractTaskObserver.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/mapper/impl/LaunchableTaskMapper.xml
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/service/impl/DefaultTaskExecuteService.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/utils/RSAUtil.java

[#350](https://github.com/WeBankFinTech/Exchangis/issues/350)
(for example:)
- New task dequeue event;
- Resolve the conflict problem in rebasing;
- Init to pre create task container for load balancer scheduler tasks in FlexibleTenancyLoadBalancer.
- Dependencies (does it add or upgrade a dependency): (no)
- Anything that affects deployment: (no)
- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (not documented)

Dev 1.1.0 perform optimize

---

exchangis-project/exchangis-project-server/pom.xml
exchangis-project/exchangis-project-server/src/main/java/com/webank/wedatasphere/exchangis/project/server/vo/ExchangisProjectAppVo.java
exchangis-project/exchangis-project-server/src/main/java/com/webank/wedatasphere/exchangis/project/server/vo/ExchangisProjectInfo.java
exchangis-server/pom.xml

Adjust the dependencies.
(for example:)
- Adjust the dependencies.
- Dependencies (does it add or upgrade a dependency): (yes / no)no
- Anything that affects deployment: (yes / no / don't know)no
- The Core framework, i.e., JobManager, Server.: (yes / no)no
- Does this pull request introduce a new feature? (yes / no)no
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

Adjust the dependencies.

---

exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/ExchangisJobExecuteAutoConfiguration.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/mapper/ExchangisJobEntityDao.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/mapper/impl/ExchangisJobEntityMapper.xml
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/restful/ExchangisJobRestfulApi.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/restful/execute/ExchangisJobExecuteRestfulApi.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/restful/execute/ExchangisTaskExecuteRestfulApi.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/restful/external/ExchangisJobDssAppConnRestfulApi.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/service/JobInfoService.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/service/impl/DefaultJobInfoService.java
exchangis-job/exchangis-job-server/src/main/java/com/webank/wedatasphere/exchangis/job/server/utils/JobAuthorityUtils.java
exchangis-project/exchangis-project-server/src/main/java/com/webank/wedatasphere/exchangis/project/server/entity/ExchangisProjectUser.java
exchangis-project/exchangis-project-server/src/main/java/com/webank/wedatasphere/exchangis/project/server/mapper/ProjectUserMapper.java
exchangis-project/exchangis-project-server/src/main/java/com/webank/wedatasphere/exchangis/project/server/mapper/impl/ProjectMapper.xml
exchangis-project/exchangis-project-server/src/main/java/com/webank/wedatasphere/exchangis/project/server/mapper/impl/ProjectUserMapper.xml
exchangis-project/exchangis-project-server/src/main/java/com/webank/wedatasphere/exchangis/project/server/restful/ExchangisProjectRestfulApi.java
exchangis-project/exchangis-project-server/src/main/java/com/webank/wedatasphere/exchangis/project/server/restful/external/ExchangisProjectDssAppConnRestfulApi.java
exchangis-project/exchangis-project-server/src/main/java/com/webank/wedatasphere/exchangis/project/server/service/ProjectService.java
exchangis-project/exchangis-project-server/src/main/java/com/webank/wedatasphere/exchangis/project/server/service/impl/ProjectServiceImpl.java
exchangis-project/exchangis-project-server/src/main/java/com/webank/wedatasphere/exchangis/project/server/vo/ExchangisProjectUserVo.java

Related issues: #50. )
[#355](https://github.com/WeBankFinTech/Exchangis/issues/355)
(for example:)
- Synchronize dss permissions to Exchangis;
- Verify the user's project, task and permission to perform tasks in exchangis;
- Create a project in dss and set query permission user, edit permission user and execute permission user.
- Use different users to perform operations on Exchangis, and judge whether they should be the corresponding permissions.
- Dependencies (does it add or upgrade a dependency): (no)
- Anything that affects deployment: (no)
- Does this pull request introduce a new feature? …

Synchronize dss permissions to Exchangis

---

docs/en_US/ch1/exchangis_appconn_deploy_en.md
docs/en_US/ch1/exchangis_datasource_en.md
docs/en_US/ch1/exchangis_deploy_en.md
docs/en_US/ch1/exchangis_sqoop_deploy_en.md
docs/zh_CN/ch1/exchangis_deploy_cn.md
docs/zh_CN/ch1/exchangis_sqoop_deploy_cn.md

**Replace the wrong URL with the correct one**
Related issue https://github.com/WeBankFinTech/Exchangis/issues/380
URL Statistics：https://github.com/WeDataSphere/Exchangis/actions/runs/2825922113/jobs/4466871982

Replace the wrong URL with the correct one 

---

docs/en_US/ch1/exchangis_appconn_deploy_en.md
docs/en_US/ch1/exchangis_deploy_en.md
docs/en_US/ch1/exchangis_sqoop_deploy_en.md
docs/zh_CN/ch1/exchangis_deploy_cn.md
docs/zh_CN/ch1/exchangis_sqoop_deploy_cn.md

**Replace the wrong URL with the correct one**
Related issue https://github.com/WeBankFinTech/Exchangis/issues/380
URL Statistics：https://github.com/WeDataSphere/Exchangis/actions/runs/2825922113/jobs/4466871982

Replace the wrong URL with the correct one

---

README-ZH.md
README.md
docs/en_US/ch1/exchangis_deploy_en.md
docs/en_US/ch1/exchangis_sqoop_deploy_en.md
docs/zh_CN/ch1/exchangis_deploy_cn.md
docs/zh_CN/ch1/exchangis_sqoop_deploy_cn.md
web/README.md

What is the purpose of the change
)
Brief change log
(for example:)
Update some docs and fix some links that cannot be used.
Verifying this change
(Please pick either of the following options)
Check the links in docs.
Does this pull request potentially affect one of the following parts:
Dependencies (does it add or upgrade a dependency): (no)
Anything that affects deployment: (no)
The Core framework, i.e., JobManager, Server.: (no)
Documentation
Does this pull request introduce a new feature? (no)
If yes, how is the feature documented? (not applicable)

Fix some links that cannot be used
